SET @MYSQL_DATABASE=IFNULL('${MYSQL_DATABASE}', 'default_db');
SET @MYSQL_USER=IFNULL('${MYSQL_USER}', 'default_user');
SET @MYSQL_PASSWORD=IFNULL('${MYSQL_PASSWORD}', 'default_password');

CREATE DATABASE IF NOT EXISTS @MYSQL_DATABASE;
CREATE USER IF NOT EXISTS @MYSQL_USER@'%' IDENTIFIED BY @MYSQL_PASSWORD;
GRANT ALL PRIVILEGES ON @MYSQL_DATABASE.* TO @MYSQL_USER@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
